services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      # Mantemos apenas o volume para dados, não para o .env
      - ./evolution_data:/evolution/data
