services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      # Mounts the local .env file into the container
      - ./.env:/evolution/.env
      # Mounts the data volume for persistence
      - ./evolution_data:/evolution/data
