version: '3.8'

services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      # Aponta para o seu banco de dados Postgres na RAILWAY
      - DATABASE_URL=SUA_URL_EXTERNA_DO_POSTGRES_DA_RAILWAY
      # Aponta para o seu Redis na RAILWAY
      - CACHE_REDIS_URI=SUA_URL_EXTERNA_DO_REDIS_DA_RAILWAY
      # Sua chave de API para proteger a Evolution API
      - AUTHENTICATION_API_KEY=SUA_API_KEY_AQUI
      # Variáveis de Configuração Essenciais
      - DATABASE_PROVIDER=postgresql
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_SAVE_INSTANCES=true
    volumes:
      - ./evolution_data:/evolution/data
