services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      # Monta o arquivo .env do servidor para dentro do container
      - ./.env:/evolution/.env
      # Monta o volume de dados para persistência da sessão
      - ./evolution_data:/evolution/data
