# docker-compose.yml para Arquitetura Híbrida (Versão Segura)
services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    env_file:
      - .env # Instrução para carregar as variáveis do arquivo .env
    volumes:
      - ./evolution_data:/evolution/data
